/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author Robert
 */
import ErrorChecking.FieldCheck;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import datahandle.Database;
import static java.lang.String.format;
import java.sql.ResultSet;
import java.sql.*;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import javax.swing.ButtonGroup;

public class JFORM extends javax.swing.JFrame {

    /**
     * Creates new form JFORM
     */
    public JFORM() throws SQLException{
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        chckboxNT = new java.awt.Checkbox();
        chckboxT = new java.awt.Checkbox();
        FName = new java.awt.Label();
        txtFname = new javax.swing.JTextField();
        GName = new javax.swing.JLabel();
        txtGname = new javax.swing.JTextField();
        MI = new javax.swing.JLabel();
        txtMI = new javax.swing.JTextField();
        Pos = new javax.swing.JLabel();
        txtPos = new javax.swing.JTextField();
        Stat = new javax.swing.JLabel();
        txtStat = new javax.swing.JTextField();
        DateEmp = new javax.swing.JLabel();
        ColDept = new javax.swing.JLabel();
        txtColdept = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        radVac = new javax.swing.JRadioButton();
        radSil = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        empdate = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        daysleavetxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Leave Form");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        chckboxNT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        chckboxNT.setLabel("Non Teaching");

        chckboxT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        chckboxT.setLabel("Teaching");
        chckboxT.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                chckboxTAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        FName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        FName.setName(""); // NOI18N
        FName.setText("Family Name:");

        GName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        GName.setText("Given Name:");

        MI.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MI.setText("MI:");

        Pos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Pos.setText("Position:");

        txtPos.setToolTipText("");

        Stat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Stat.setText("Status:");

        DateEmp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        DateEmp.setText("Date Of Employment:");

        ColDept.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ColDept.setText("College/Dept.");

        txtColdept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColdeptActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        jLabel2.setText("Kinds of Leave:");

        radVac.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        radVac.setText("Vacation");
        radVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radVacActionPerformed(evt);
            }
        });

        radSil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        radSil.setText("SIL");
        radSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSilActionPerformed(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Number of Day(s) Leave: ");

        daysleavetxt.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DateEmp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(empdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Pos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ColDept)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtColdept, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(39, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Stat)
                                .addGap(270, 270, 270))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(GName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtStat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtGname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MI)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMI, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radSil)
                                    .addComponent(radVac)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(chckboxNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(chckboxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(daysleavetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator3)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(btnSubmit)
                .addGap(94, 94, 94)
                .addComponent(btnCancel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GName)
                            .addComponent(txtGname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MI)
                            .addComponent(txtMI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chckboxNT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chckboxT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Stat)
                        .addComponent(txtStat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pos)
                        .addComponent(txtPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateEmp)
                    .addComponent(ColDept)
                    .addComponent(txtColdept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radVac, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radSil, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysleavetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnCancel))
                .addGap(265, 265, 265))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtColdeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColdeptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColdeptActionPerformed

    private void radVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radVacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radVacActionPerformed

    private void radSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radSilActionPerformed

    public void updateDB(){
        
        try{
        db = new Database();
        
        String query,query2,insert;
        

        Date tempdate = empdate.getDate();
      
        Boolean flag = false;
 
       DateFormat date = new SimpleDateFormat("yyyy-MM-dd");
     
       
       String sempdate = date.format(tempdate);
        
       
       
        
        query = "SELECT * FROM teachingdata_table WHERE fam_name='"+txtFname.getText()+"' AND given_name='"+txtGname.getText()+"'";
        query2 = "SELECT * FROM nonteachingdata_table  WHERE fam_name='"+txtFname.getText()+"' AND given_name='"+txtGname.getText()+"'";
        Statement stmt = db.conn.createStatement();
        Statement stmt2 = db.conn.createStatement();
        ResultSet rs = stmt.executeQuery(query);
        ResultSet rs2 = stmt2.executeQuery(query2);
        
        
        String dateleave = daysleavetxt.getText();
        int numdays = Integer.parseInt(dateleave);
        int id = 0;
        long vl = 15, newvl = 0;
        long sil = 5, newsil = 0;
        
       
            newvl = vl;
            newsil = sil;
           
            if(radVac.isSelected()){
                
                     newvl = vl - numdays;
                
            }else if(radSil.isSelected()){
              
                    newsil = sil - numdays;
                }
                else{
                 JOptionPane.showMessageDialog(null, "Please select the type of leave.");
                }  
          
        // txtFname txtGname txtMI txtPos txtStat txtColdept DateEmp
        if (chckboxT.getState()){
            
           if( newvl >= 0 && newsil >= 0){
            if(rs.next()){
                flag = true;
                JOptionPane.showMessageDialog(null, "Employee already exists");
            }else {
            
            insert = "INSERT INTO teachingdata_table (id, fam_name, given_name, mi , position , status , college , date_employment, vl, sil) "
                 + "VALUES ('"+id+"','"+txtFname.getText()+"','"+txtGname.getText()+"','"+txtMI.getText()+"','"+txtPos.getText()+"','"+txtStat.getText()+"','"+txtColdept.getText()+"',"
                 + "'"+sempdate+"','"+newvl+"','"+newsil+"')"; 
        
            stmt.executeUpdate(insert);
            }
            rs.close();
           } else{
               JOptionPane.showMessageDialog(null, "Days must not exceed total number of leaves.");
           }
        }
        
       else if (chckboxNT.getState()){
            if(newvl >= 0 && newsil >= 0){   
            if(rs2.next()){
                 JOptionPane.showMessageDialog(null, "Employee already exists");
            } else {
                
            insert = "INSERT INTO nonteachingdata_table (id, fam_name, given_name, mi , position , status , college , date_employment, vl, sil) "
                 + "VALUES ('"+id+"','"+txtFname.getText()+"','"+txtGname.getText()+"','"+txtMI.getText()+"','"+txtPos.getText()+"','"+txtStat.getText()+"','"+txtColdept.getText()+"',"
                 + "'"+sempdate+"','"+newvl+"','"+newsil+"')"; 
        
            stmt.executeUpdate(insert);
            }
            rs2.close();
            }else{
               JOptionPane.showMessageDialog(null, "Days must not exceed total number of leaves.");
           }
        }else{
             JOptionPane.showMessageDialog(null, "Choose between Teaching and Non-Teaching");
        }
         
            stmt.close();
            stmt2.close();
           // rs2.close();
            db.closeConn();
        } catch (SQLException ex) {
            Logger.getLogger(JFORM.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace(System.err);

            JOptionPane.showMessageDialog(null, "SQLState: " + ((SQLException)ex).getSQLState()+ "\nError Code: " 
                    + ((SQLException)ex).getErrorCode() + "\nMessage: " + ex.getMessage());
        }
        
    }
    
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to exit the program?", "Exit Program Message Box",
        JOptionPane.YES_NO_OPTION);

    if (confirmed == JOptionPane.YES_OPTION) {
      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
     setVisible(false);
    } 
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
       if (!new FieldCheck().checkFields(fieldList)){ //checks if fields are empty/do not contain ; NEED TO IMPLEMENT
            int input = JOptionPane.showConfirmDialog(null, "Are you sure you would like to submit? Alteration of Personal data will no longer be possible.");
            if (input==0) {
                updateDB();
                this.dispose();
            }
        }
           
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
             int input = JOptionPane.showConfirmDialog(null, "Are you sure you would like to close this form? Unsaved information will be lost.");
        if (input==0) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing
    
    /* private void setCalendar(String format, String startingDate) {
        SimpleDateFormat df = new SimpleDateFormat(format);
        try {
            Date startdate = df.parse(startingDate);
         
           empdate.setDate(startdate);
          // datefiled.setDate(startdate);
            
        } catch (ParseException ex) {
            Logger.getLogger(JFORM.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Message: " + ex.getMessage());
        }
    } */
      
    
      Date now;
    
   /* private void setDateTime(){
        now = new Date();
        DateFormat date = new SimpleDateFormat("yyyy/MM/dd");
       // DateFormat time = new SimpleDateFormat("HH:mm:ss");
       // leavefrom.setDate(date.format(now));
    } */
    
    ArrayList fieldList;
   
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        ButtonGroup btngroup0 = new ButtonGroup();
        fieldList = new ArrayList();
        fieldList.add(txtFname);
        fieldList.add(txtGname);
        //fieldList.add(txtMI);
        fieldList.add(txtPos);
        fieldList.add(txtStat);
        fieldList.add(txtColdept);
         fieldList.add(daysleavetxt);
         btngroup0.add(radVac);
         btngroup0.add(radSil);
  
        //getCalendar();       
        //setCalendar("yyyy-mm-dd", "1999-01-01");
       /* fieldList.add(empdate);
        fieldList.add(datefiled);
        fieldList.add(leavefrom);
        fieldList.add(leaveto); */
        
    }//GEN-LAST:event_formWindowOpened

    private void chckboxTAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_chckboxTAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_chckboxTAncestorMoved

    /**
     * @param args the command line arguments
     */
    
    
     private Database db;
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFORM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFORM().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFORM.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ColDept;
    private javax.swing.JLabel DateEmp;
    private java.awt.Label FName;
    private javax.swing.JLabel GName;
    private javax.swing.JLabel MI;
    private javax.swing.JLabel Pos;
    private javax.swing.JLabel Stat;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup btngroup;
    private java.awt.Checkbox chckboxNT;
    private java.awt.Checkbox chckboxT;
    private javax.swing.JTextField daysleavetxt;
    private org.jdesktop.swingx.JXDatePicker empdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton radSil;
    private javax.swing.JRadioButton radVac;
    private javax.swing.JTextField txtColdept;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtGname;
    private javax.swing.JTextField txtMI;
    private javax.swing.JTextField txtPos;
    private javax.swing.JTextField txtStat;
    // End of variables declaration//GEN-END:variables


}
